# Site settings
site_name: asdf.land
site_tagline: The only URL shortener you'll ever need.

# The server port
port: 9090

# Right now only "redis" is supported
db_kind: redis

# Redis configuration
redis_addr: localhost:6379
redis_dbnum: 7
redis_pass: 

# The password hashing cost. higher -> slower, more secure
bcrypt_cost: 8

# The delimiter for readable links with multiple words
# e.g. your.site/cat.dog.fox for a "." delimiter
word_delimiter: "."
